// Film stocks, cameras, and print processes. Each entry is written in the
// vocabulary of the research notes (gray-ramp anchors, contrast slope, named
// hue bands, grain σ) and compiled down to a FilmRecipe by `stock()`.
//
// Numbers are design values tuned by eye against reference scans, not
// measured characteristic curves. Stock names are trademarks of their owners;
// these are interpretations, not affiliated products.

import { NEUTRAL, hex3, type FilmRecipe, type Vec3 } from "./film";

export type FilmCategory = {
  id: string;
  label: string;
  blurb: string;
};

export const FILM_CATEGORIES: FilmCategory[] = [
  {
    id: "negative",
    label: "NEGATIVE",
    blurb:
      "C-41 colour negative — the everyday film of weddings, holidays, and shoeboxes. Forgiving highlights, warm skin.",
  },
  {
    id: "slide",
    label: "SLIDE & SCREEN",
    blurb:
      "Reversal and motion-picture stocks: crushed blacks, dye-deep colour, cinema print curves, halation.",
  },
  {
    id: "lab",
    label: "LAB & DECAY",
    blurb:
      "Happy accidents: the wrong chemistry, film loaded backwards, false-colour infrared, expired rolls, prints that lost their cyan.",
  },
  {
    id: "camera",
    label: "CAMERAS",
    blurb:
      "When the camera is the look: instant prints, plastic lenses, light leaks, on-camera flash, a Super 8 gate.",
  },
  {
    id: "antique",
    label: "ANTIQUE",
    blurb:
      "Silver, iron, and pigment, 1839–1950 — with their real spectral blindness. Tintypes can't see red; cyanotypes are Prussian blue.",
  },
  {
    id: "afterdark",
    label: "AFTERDARK",
    blurb:
      "Night vision, flash, VHS, xerox and dithered grunge — the crunchy, gothic edits of underground rap and IG goth.",
  },
  {
    id: "polypaint",
    label: "PS2 & PAINT",
    blurb:
      "Your photo as a PS2-era low-poly model — hard polygon edges, airbrushed insides, cut out on flat colour — plus sticker and oil-paint restyles.",
  },
  {
    id: "machine",
    label: "SCREENS & MACHINES",
    blurb:
      "Your photo through a machine: CRT tubes, a receipt printer, 1-bit computer screens, a depth sensor, a blob tracker, a broken video codec.",
  },
  {
    id: "earth",
    label: "EARTH & AUTEUR",
    blurb:
      "Earth-tone grades and the palettes of photographers and filmmakers: matte, muted, golden, moss, terracotta, neon.",
  },
];

export type FilmStock = {
  id: string;
  name: string;
  category: string;
  /** Short readout line: ISO · process · era. */
  meta: string;
  /** One-line card hint. */
  hint: string;
  /** A sentence of lore — why it looks the way it does. */
  note: string;
  recipe: FilmRecipe;
};

// ───────────────────────────────────────────────────────────────────────────
// Builder
// ───────────────────────────────────────────────────────────────────────────

type BandName = "R" | "O" | "Y" | "G" | "A" | "B" | "P" | "M";
type BandAdj = { h?: number; s?: number; l?: number };

const BAND_DEG: Record<BandName, number> = {
  R: 0,
  O: 30,
  Y: 60,
  G: 120,
  A: 180,
  B: 220,
  P: 270,
  M: 320,
};

type Spec = Partial<FilmRecipe> & {
  id: string;
  name: string;
  category: string;
  meta: string;
  hint: string;
  note: string;
  /** White balance gains in linear light. */
  wbLin?: Vec3;
  /** Slope at the 0.5 pivot is 1 + con. */
  con?: number;
  /** Where a neutral ramp lands: black, 18% gray, white. */
  ramp?: [string, string, string];
  /** Named hue-band tweaks: h = degrees, s/l = percent. */
  bands?: Partial<Record<BandName, BandAdj>>;
  /** Explicit 12-band hue shifts (degrees), for wholesale colour remaps. */
  hue12?: number[];
  /** Grain σ at the midtone peak, in 0–1 display units. */
  grainSigma?: number;
  /** Same-weights mono mixer. */
  mono?: Vec3;
  /** Dye-transfer separation: c' = c + k·(c − mean(others)). */
  separate?: number;
};

// Gaussian band weights (σ ≈ 25°), evaluated at the 12 engine bands. Sums are
// capped at 1 so neighbouring tweaks average instead of stacking.
function compileBands(spec: Partial<Record<BandName, BandAdj>>) {
  const hue: number[] = [];
  const sat: number[] = [];
  const lum: number[] = [];
  for (let k = 0; k < 12; k++) {
    const at = k * 30;
    let wsum = 0;
    let h = 0;
    let s = 0;
    let l = 0;
    for (const [name, adj] of Object.entries(spec) as [BandName, BandAdj][]) {
      let dd = Math.abs(at - BAND_DEG[name]) % 360;
      if (dd > 180) dd = 360 - dd;
      const wgt = Math.exp(-(dd * dd) / (2 * 25 * 25));
      wsum += wgt;
      h += (adj.h ?? 0) * wgt;
      s += (adj.s ?? 0) * wgt;
      l += (adj.l ?? 0) * wgt;
    }
    const n = Math.max(1, wsum);
    hue.push(h / n);
    sat.push(1 + s / n / 100);
    lum.push(1 + l / n / 100);
  }
  return { hue, sat, lum };
}

function stock(spec: Spec): FilmStock {
  const {
    id,
    name,
    category,
    meta,
    hint,
    note,
    wbLin,
    con,
    ramp,
    bands,
    hue12,
    grainSigma,
    mono,
    separate,
    ...rest
  } = spec;
  const r: FilmRecipe = { ...NEUTRAL, ...rest };

  if (wbLin) r.wb = wbLin.map((v) => Math.pow(v, 1 / 2.2)) as Vec3;
  if (con !== undefined) r.contrast = con * 2;
  if (grainSigma !== undefined) r.grain = grainSigma * 20;
  if (mono) {
    r.mix = [mono, mono, mono];
    r.sat = 0;
  }
  if (separate) {
    const k = separate;
    r.mix = [
      [1 + k, -k / 2, -k / 2],
      [-k / 2, 1 + k, -k / 2],
      [-k / 2, -k / 2, 1 + k],
    ];
  }
  if (bands) {
    const b = compileBands(bands);
    r.hue = b.hue;
    r.satBand = b.sat;
    r.lumBand = b.lum;
  }
  if (hue12) r.hue = hue12;

  if (ramp) {
    // Solve per-channel gamma so 18% gray lands on the mid anchor, after
    // exposure, WB, contrast and shoulder have had their say.
    const [b, m, w] = ramp.map(hex3);
    const e = Math.pow(2, r.exposure);
    const lift: number[] = [];
    const gain: number[] = [];
    const gamma: number[] = [];
    for (let i = 0; i < 3; i++) {
      let v = Math.min(1, 0.46 * r.wb[i] * e);
      const s = v * v * (3 - 2 * v);
      v = v + r.contrast * (s - v);
      if (r.shoulder > 0) v = (v * (1 + r.shoulder)) / (1 + r.shoulder * v);
      v = Math.min(0.99, Math.max(0.01, v));
      const t = Math.min(0.98, Math.max(0.02, (m[i] - b[i]) / Math.max(0.02, w[i] - b[i])));
      lift.push(b[i]);
      gain.push(w[i]);
      gamma.push(Math.min(3, Math.max(0.33, Math.log(v) / Math.log(t))));
    }
    r.lift = lift as Vec3;
    r.gain = gain as Vec3;
    r.gamma = gamma as Vec3;
  }
  return { id, name, category, meta, hint, note, recipe: r };
}

const PAN_TRIX: Vec3 = [0.28, 0.5, 0.22];
const PAN: Vec3 = [0.3, 0.55, 0.15];

// ───────────────────────────────────────────────────────────────────────────
// Stocks
// ───────────────────────────────────────────────────────────────────────────

export const FILM_STOCKS: FilmStock[] = [
  // ── NEGATIVE ────────────────────────────────────────────────────────────
  stock({
    id: "portra400",
    name: "PORTRA 400",
    category: "negative",
    meta: "ISO 400 · C-41 · 1998",
    hint: "golden skin, creamy whites",
    note: "The wedding-and-portrait standard. Warm amber shadows, skin that glows instead of reddens, olive greens, and a shoulder so long it almost never clips.",
    wbLin: [1.03, 1, 0.95],
    ramp: ["#1f1a15", "#7a736a", "#f6eee2"],
    con: -0.1,
    shoulder: 0.4,
    sat: 0.9,
    bands: {
      R: { h: 3, s: -10 },
      O: { s: -12, l: 4 },
      Y: { h: -6, s: -10 },
      G: { h: -15, s: -30, l: -5 },
      A: { s: -20 },
      B: { h: -5, s: -10 },
    },
    shadowTint: "#3a2c1e",
    shadowAmt: 0.1,
    highTint: "#fff0da",
    highAmt: 0.06,
    grainSigma: 0.022,
    grainSize: 1.4,
    grainChroma: 0.15,
  }),
  stock({
    id: "portra160",
    name: "PORTRA 160",
    category: "negative",
    meta: "ISO 160 · C-41 · 1998",
    hint: "softer, paler, finer",
    note: "Portra's quiet sibling: lower saturation and contrast, near-invisible grain. Studio and daylight portraits where skin must stay calm.",
    wbLin: [1.01, 1, 0.98],
    ramp: ["#211c18", "#7c766e", "#f7f0e6"],
    con: -0.15,
    shoulder: 0.45,
    sat: 0.84,
    bands: {
      O: { s: -14, l: 5 },
      Y: { h: -6, s: -12 },
      G: { h: -12, s: -30 },
      A: { s: -20 },
      B: { s: -12 },
    },
    highTint: "#fff3e2",
    highAmt: 0.05,
    grainSigma: 0.014,
    grainSize: 1.2,
    grainChroma: 0.1,
  }),
  stock({
    id: "portra800",
    name: "PORTRA 800",
    category: "negative",
    meta: "ISO 800 · C-41 · 1998",
    hint: "night warmth, teal shadows",
    note: "The low-light Portra. More saturation and bite; underexposed shadows slide toward teal-green while skin stays warm.",
    wbLin: [1.03, 1, 0.95],
    ramp: ["#1a1a17", "#78726a", "#f6ede0"],
    con: 0.05,
    shoulder: 0.3,
    sat: 1,
    bands: {
      O: { s: -8, l: 3 },
      Y: { h: -6 },
      G: { h: -12, s: -20 },
      B: { h: -5 },
    },
    shadowTint: "#23302c",
    shadowAmt: 0.12,
    highTint: "#fff0da",
    highAmt: 0.05,
    grainSigma: 0.04,
    grainSize: 1.9,
    grainChroma: 0.2,
  }),
  stock({
    id: "gold200",
    name: "GOLD 200",
    category: "negative",
    meta: "ISO 200 · C-41 · 1988",
    hint: "90s holiday print",
    note: "The drugstore film. A yellow wash over everything, reds and yellows first in line, skies a slightly dull cyan — every family album from the 90s.",
    wbLin: [1.06, 1.01, 0.88],
    ramp: ["#221a10", "#7e735f", "#fff3d6"],
    con: 0.1,
    sat: 1.08,
    bands: {
      O: { s: 8, l: 3 },
      Y: { h: -5, s: 15 },
      G: { h: -12, s: -5 },
      B: { h: -8, s: -8 },
    },
    highTint: "#ffe7a8",
    highAmt: 0.12,
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0.2,
  }),
  stock({
    id: "ektar100",
    name: "EKTAR 100",
    category: "negative",
    meta: "ISO 100 · C-41 · 2008",
    hint: "slide-punchy negative",
    note: "The world's finest-grain colour negative and the most saturated. Reds punch, skies go deep — and skin famously turns red-magenta.",
    wbLin: [1, 1, 1.02],
    ramp: ["#0e0e10", "#737476", "#fbfbf8"],
    con: 0.25,
    sat: 1.3,
    bands: {
      R: { s: 25 },
      O: { h: -4, s: 12 },
      Y: { s: 10 },
      G: { s: 10 },
      A: { s: 15 },
      B: { s: 25, l: -10 },
    },
    grainSigma: 0.008,
    grainSize: 1,
    grainChroma: 0.05,
    vignette: 0.1,
  }),
  stock({
    id: "superia400",
    name: "SUPERIA 400",
    category: "negative",
    meta: "ISO 400 · C-41 · 1998",
    hint: "fuji greens, cool shadows",
    note: "Fuji's consumer workhorse. Greens pulled toward teal, a faint green-cyan in the shadows, pinker skin, and plenty of chroma noise from the minilab scanner.",
    wbLin: [0.99, 1.02, 1],
    ramp: ["#182019", "#727671", "#f4f6f1"],
    con: 0.1,
    sat: 1.1,
    bands: {
      R: { h: 4, s: 10 },
      O: { h: 3, s: -5 },
      Y: { h: 5 },
      G: { h: 10, s: 10 },
      A: { s: 10 },
      B: { h: 5, s: 10 },
    },
    shadowTint: "#1c2a24",
    shadowAmt: 0.12,
    grainSigma: 0.035,
    grainSize: 1.6,
    grainChroma: 0.3,
  }),
  stock({
    id: "c200",
    name: "FUJICOLOR C200",
    category: "negative",
    meta: "ISO 200 · C-41 · 2000s",
    hint: "pastel, cool, cheap",
    note: "The budget Fuji. Muted, pastel, cool-leaning and a little flat — which is exactly why people still hunt for it.",
    wbLin: [0.99, 1.01, 1.02],
    ramp: ["#1a201c", "#747775", "#f2f5f4"],
    con: 0,
    sat: 0.95,
    bands: {
      O: { h: 5 },
      G: { h: 10, s: 5 },
      B: { h: 5 },
    },
    shadowTint: "#1c2a24",
    shadowAmt: 0.08,
    grainSigma: 0.025,
    grainSize: 1.5,
    grainChroma: 0.25,
  }),
  stock({
    id: "pro400h",
    name: "PRO 400H",
    category: "negative",
    meta: "ISO 400 · C-41 · †2021",
    hint: "mint greens, airy +1",
    note: "Discontinued and mourned. Mint greens, cool neutral skin, a whisper of magenta in the shadows — always shot a stop over for the airy wedding look.",
    exposure: 0.3,
    wbLin: [0.99, 1.01, 1.02],
    ramp: ["#2a2530", "#7b7c7c", "#f5f7f3"],
    con: -0.25,
    sat: 0.8,
    bands: {
      R: { h: 5 },
      O: { s: -15, l: 8 },
      Y: { h: 8, s: -20 },
      G: { h: 22, s: -10, l: 10 },
      A: { s: -10, l: 5 },
      B: { h: -6, s: -10, l: 5 },
    },
    grainSigma: 0.018,
    grainSize: 1.3,
    grainChroma: 0.1,
  }),
  stock({
    id: "vista200",
    name: "AGFA VISTA 200",
    category: "negative",
    meta: "ISO 200 · C-41 · †2018",
    hint: "red-forward, cyan skies",
    note: "Agfa's last consumer film: warm, red-forward, cyan-blue skies, colour 'beyond reality'. Sold for pennies at Poundland until it was gone.",
    wbLin: [1.04, 1, 0.95],
    ramp: ["#16161a", "#78726e", "#faf5ec"],
    con: 0.2,
    sat: 1.2,
    bands: {
      R: { s: 25, l: -5 },
      O: { s: 5 },
      G: { h: -5, s: 5 },
      A: { s: 15 },
      B: { h: -10, s: 15 },
    },
    grainSigma: 0.028,
    grainSize: 1.5,
    grainChroma: 0.2,
  }),
  stock({
    id: "orwo500",
    name: "WOLFEN NC500",
    category: "negative",
    meta: "ISO 400 · C-41 · 2023",
    hint: "east-german green-yellow",
    note: "Agfa heritage from the old Wolfen plant. No orange mask and a weak yellow dye: very green-yellow, desaturated, muted skies, crisp chunky grain.",
    exposure: -0.15,
    wbLin: [1.02, 1.04, 0.88],
    ramp: ["#1c1f16", "#76765f", "#f1edd0"],
    con: -0.1,
    sat: 0.72,
    bands: {
      R: { s: -20 },
      O: { s: -10 },
      Y: { s: 10 },
      G: { h: -6, s: 5 },
      A: { s: -30 },
      B: { s: -45, l: 5 },
    },
    grainSigma: 0.05,
    grainSize: 1.5,
    grainChroma: 0.2,
  }),

  // ── SLIDE & SCREEN ──────────────────────────────────────────────────────
  stock({
    id: "kodachrome64",
    name: "KODACHROME 64",
    category: "slide",
    meta: "ISO 64 · K-14 · 1974–2009",
    hint: "deep reds, cyan blues",
    note: "Dyes added during development, not in the film — so reds come out deep and true. Contrasty, golden yellows, cyan-leaning blues, grain like silk. The National Geographic look.",
    wbLin: [1.03, 1, 0.96],
    ramp: ["#120e0b", "#6f6a64", "#f8f4ec"],
    con: 0.35,
    sat: 1.15,
    bands: {
      R: { h: -3, s: 25, l: -8 },
      O: { s: 5 },
      Y: { h: -5, s: 15 },
      G: { h: -10, s: -15, l: -5 },
      B: { h: -12, s: 10, l: -12 },
    },
    grainSigma: 0.01,
    grainSize: 1,
    grainChroma: 0.05,
  }),
  stock({
    id: "herzog",
    name: "HERZOG '58",
    category: "slide",
    meta: "KODACHROME · VANCOUVER · 1950s",
    hint: "street kodachrome, aged",
    note: "After Fred Herzog's 1950s Vancouver street slides: Kodachrome warmed by age, muted greens, red signage and coats carrying the frame.",
    wbLin: [1.05, 1, 0.93],
    ramp: ["#17110d", "#6b655c", "#f6efe2"],
    con: 0.3,
    sat: 1.1,
    bands: {
      R: { h: -3, s: 25, l: -8 },
      Y: { h: -5, s: 10 },
      G: { h: -10, s: -25, l: -5 },
      B: { h: -12, s: 5, l: -10 },
    },
    vignette: 0.15,
    grainSigma: 0.012,
    grainSize: 1.1,
    grainChroma: 0.05,
  }),
  stock({
    id: "velvia50",
    name: "VELVIA 50",
    category: "slide",
    meta: "ISO 50 · E-6 · 1990",
    hint: "hyper-saturated landscape",
    note: "The landscape photographer's drug. Hyper-saturated, separated greens, deep blues, crushed blacks, a magenta lean in the mids.",
    wbLin: [1.02, 0.97, 1.02],
    ramp: ["#0a090c", "#6a666b", "#fbf8fb"],
    con: 0.45,
    sat: 1.45,
    bands: {
      R: { h: -5, s: 30 },
      Y: { s: 20 },
      G: { s: 30, l: -10 },
      A: { s: 20 },
      B: { s: 35, l: -15 },
      M: { s: 15 },
    },
    shadowTint: "#0e1410",
    shadowAmt: 0.08,
    grainSigma: 0.006,
    grainSize: 1,
    grainChroma: 0.05,
  }),
  stock({
    id: "provia",
    name: "PROVIA 100F",
    category: "slide",
    meta: "ISO 100 · E-6 · 2000",
    hint: "clean, neutral slide",
    note: "The honest slide. Neutral, crisp, cool-clean blacks — what a light table looks like when nothing is trying to flatter you.",
    wbLin: [0.99, 1, 1.02],
    ramp: ["#0c0e12", "#6e6e70", "#fafafa"],
    con: 0.3,
    sat: 1.15,
    bands: { B: { s: 15 } },
    grainSigma: 0.007,
    grainSize: 1,
    grainChroma: 0.05,
  }),
  stock({
    id: "eterna",
    name: "ETERNA",
    category: "slide",
    meta: "ISO 250 · ECN-2 · 2004",
    hint: "flat cinema, teal shadows",
    note: "Fuji's motion-picture negative, made to be graded: the lowest contrast and saturation in their range, cyan-shifted blues, soft teal shadows. Letterboxed.",
    ramp: ["#182224", "#74777a", "#eee8dc"],
    con: -0.25,
    sat: 0.8,
    bands: {
      R: { s: -15 },
      O: { s: -5 },
      Y: { h: 5, s: -20 },
      G: { h: 12, s: -25 },
      B: { h: 5, s: -15 },
    },
    shadowTint: "#1a2a2c",
    shadowAmt: 0.15,
    highTint: "#f0e2cc",
    highAmt: 0.05,
    grainSigma: 0.018,
    grainSize: 1.5,
    grainChroma: 0.1,
    border: "letterbox",
    paper: "#000000",
  }),
  stock({
    id: "vision2383",
    name: "VISION3 → 2383",
    category: "slide",
    meta: "5207 NEG → PRINT · CINEMA",
    hint: "the film-print look",
    note: "Camera negative printed onto 2383 release stock — the colorist's 'film print' and the true origin of teal-and-orange. The remjet backing means no halation.",
    wbLin: [1.02, 1, 0.97],
    ramp: ["#0c1418", "#73706b", "#fff2de"],
    con: 0.3,
    shoulder: 0.3,
    sat: 1.05,
    bands: {
      O: { h: -3, s: 8 },
      Y: { h: -10 },
      G: { h: -15, s: -20 },
      A: { s: -10 },
      B: { h: -15, s: 5 },
    },
    shadowTint: "#10262a",
    shadowAmt: 0.15,
    highTint: "#ffe2b8",
    highAmt: 0.1,
    grainSigma: 0.015,
    grainSize: 1.2,
    grainChroma: 0.1,
  }),
  stock({
    id: "cinestill800t",
    name: "CINESTILL 800T",
    category: "slide",
    meta: "ISO 800 · TUNGSTEN 3200K",
    hint: "neon nights, red halos",
    note: "Vision3 with the remjet stripped off: light bounces off the base into the red layer, so every street lamp grows a red-orange halo. Tungsten-balanced, so daylight goes blue.",
    wbLin: [0.9, 1, 1.15],
    ramp: ["#0d161c", "#6e7276", "#f2f6f7"],
    con: 0.1,
    sat: 1.1,
    bands: {
      O: { s: -10, l: 8 },
      G: { h: 12, s: -10 },
      A: { s: 10 },
      B: { h: -10, s: 10 },
    },
    glow: 0.7,
    glowColor: "#ff3810",
    glowThreshold: 0.78,
    glowRadius: 0.015,
    grainSigma: 0.04,
    grainSize: 1.8,
    grainChroma: 0.2,
  }),
  stock({
    id: "cinestill50d",
    name: "CINESTILL 50D",
    category: "slide",
    meta: "ISO 50 · DAYLIGHT 5500K",
    hint: "clean cinema + halo",
    note: "The daylight CineStill: the fine-grained Vision3 50D print look, with a soft red halation creeping around the brightest highlights.",
    wbLin: [1.02, 1, 0.97],
    ramp: ["#0c1418", "#74716c", "#fff4e2"],
    con: 0.25,
    shoulder: 0.3,
    sat: 1.08,
    bands: {
      O: { h: -3, s: 8 },
      Y: { h: -8 },
      G: { h: -12, s: -15 },
      B: { h: -12, s: 8 },
    },
    shadowTint: "#10262a",
    shadowAmt: 0.12,
    highTint: "#ffe2b8",
    highAmt: 0.08,
    glow: 0.25,
    glowColor: "#ff3810",
    glowThreshold: 0.8,
    glowRadius: 0.012,
    grainSigma: 0.01,
    grainSize: 1.1,
    grainChroma: 0.08,
  }),
  stock({
    id: "technicolor3",
    name: "TECHNICOLOR 3-STRIP",
    category: "slide",
    meta: "DYE TRANSFER · 1932–1955",
    hint: "oz, separated dyes",
    note: "Three separate black-and-white records, each printed in its own dye. Colours that never bleed into each other — the saturated, glowing studio world of 1939.",
    separate: 0.3,
    wbLin: [1.03, 1, 0.97],
    ramp: ["#0b0a0e", "#716a68", "#fbf5ee"],
    con: 0.25,
    sat: 1,
    bands: {
      R: { s: 20, l: -5 },
      O: { h: -3, s: 10 },
      G: { h: 5, s: 10 },
      B: { s: 20 },
    },
    glow: 0.12,
    glowColor: "#fff2e0",
    glowThreshold: 0.7,
    glowRadius: 0.012,
    grainSigma: 0.01,
    grainSize: 1.1,
    grainChroma: 0.05,
  }),
  stock({
    id: "eggleston",
    name: "DYE TRANSFER '73",
    category: "slide",
    meta: "AFTER EGGLESTON · RED CEILING",
    hint: "crimson, southern heat",
    note: "After William Eggleston's dye-transfer prints: no other process could hold a red that saturated. Crimson ceilings, humid greens, ordinary things made unbearable.",
    separate: 0.25,
    ramp: ["#120c0b", "#6d6660", "#faf4e6"],
    con: 0.3,
    bands: {
      R: { h: -4, s: 35, l: -12 },
      Y: { s: 15 },
      G: { h: -5, s: 15, l: -8 },
      B: { h: -6, s: 5 },
    },
    grainSigma: 0.012,
    grainSize: 1.2,
    grainChroma: 0.08,
  }),
  stock({
    id: "twostrip",
    name: "TECHNICOLOR 2-STRIP",
    category: "slide",
    meta: "PROCESS 3 · 1922–1932",
    hint: "no blue exists",
    note: "Only two records — red-orange and blue-green — so blue simply cannot be reproduced. Skies go teal, skin coral, yellows peach. The colour of early talkies.",
    mix: [
      [1, 0, 0],
      [0, 0.48, 0.48],
      [0, 0.45, 0.45],
    ],
    ramp: ["#1a0f0c", "#76695f", "#f7ebdd"],
    con: 0.15,
    sat: 1.15,
    grainSigma: 0.02,
    grainSize: 1.4,
    grainChroma: 0.1,
  }),
  stock({
    id: "bleach",
    name: "BLEACH BYPASS",
    category: "slide",
    meta: "SKIP-BLEACH · ENR",
    hint: "silver left in, metallic",
    note: "Skip the bleach and the silver stays on top of the dyes: half the colour gone, blacks crushed, a cold metallic sheen. Saving Private Ryan, Se7en.",
    wbLin: [0.98, 1, 1.01],
    ramp: ["#08090a", "#6d6e6e", "#f4f4f0"],
    con: 0.5,
    sat: 0.45,
    grainSigma: 0.04,
    grainSize: 1.6,
    grainChroma: 0,
  }),

  // ── LAB & DECAY ─────────────────────────────────────────────────────────
  stock({
    id: "xpro",
    name: "CROSS-PROCESS",
    category: "lab",
    meta: "E-6 IN C-41 · LOMO LC-A",
    hint: "indigo shadows, acid highs",
    note: "Slide film developed in negative chemistry. Contrast blows out, shadows go indigo, highlights acid yellow-green — the 90s Lomo LC-A look, tunnel vignette included.",
    ramp: ["#080533", "#8c8f78", "#fff7bd"],
    con: 0.45,
    sat: 1.3,
    bands: { G: { h: -10 } },
    vignette: 0.45,
    vignetteFalloff: 0.55,
    grainSigma: 0.035,
    grainSize: 1.6,
    grainChroma: 0.3,
  }),
  stock({
    id: "redscale",
    name: "REDSCALE",
    category: "lab",
    meta: "FILM LOADED BACKWARDS",
    hint: "red at box speed",
    note: "Roll the film in backwards and light passes through the base first, hitting the red-sensitive layer hardest. Everything becomes ember, rust and amber.",
    mono: [0.35, 0.5, 0.15],
    tone: ["#1a0503", "#a8400f", "#f7d894"],
    toneMix: 0.87,
    sat: 1,
    con: 0.1,
    grainSigma: 0.045,
    grainSize: 1.7,
    grainChroma: 0.1,
    vignette: 0.2,
  }),
  stock({
    id: "redscalexl",
    name: "REDSCALE XL",
    category: "lab",
    meta: "BACKWARDS · +3 STOPS",
    hint: "overexposed to gold",
    note: "Redscale overexposed by a few stops: the red burns through to orange and honey-yellow, like a photograph of late afternoon from inside a jar.",
    mono: [0.35, 0.5, 0.15],
    tone: ["#2a0a04", "#e28f3a", "#f9e6a8"],
    toneMix: 0.85,
    sat: 1,
    grainSigma: 0.04,
    grainSize: 1.7,
    grainChroma: 0.1,
    vignette: 0.15,
  }),
  stock({
    id: "lomopurple",
    name: "LOMOCHROME PURPLE",
    category: "lab",
    meta: "ISO 100–400 · C-41 · 2013",
    hint: "green leaves turn violet",
    note: "A film engineered to be wrong: foliage turns purple, blues turn aqua-green, yellows turn pink — while reds stay put, so skin still looks human.",
    // Wholesale remap, written unwrapped so neighbouring bands stay continuous.
    hue12: [0, 0, -85, -140, -195, -240, -380, -385, -405, -375, -365, -360],
    satBand: [1, 1.1, 1.05, 1.15, 1.15, 1.05, 0.85, 0.8, 0.85, 1, 1, 1],
    ramp: ["#120e16", "#72696f", "#f6f0ee"],
    con: 0.1,
    sat: 1.1,
    grainSigma: 0.035,
    grainSize: 1.6,
    grainChroma: 0.25,
  }),
  stock({
    id: "metropolis",
    name: "LOMOCHROME METROPOLIS",
    category: "lab",
    meta: "ISO 100–400 · C-41 · 2019",
    hint: "colour film noir",
    note: "Desaturated, high-contrast, deep blacks, the palette dragged toward yellow, green and cyan. Concrete cities on an overcast day.",
    wbLin: [1, 1.02, 0.94],
    ramp: ["#0b0d0b", "#6c6c62", "#f2eedc"],
    con: 0.35,
    sat: 0.45,
    bands: {
      R: { h: 8, s: -45 },
      O: { h: 5, s: -20 },
      G: { h: -5, s: -25 },
      A: { s: -20 },
      B: { h: -10, s: -40 },
    },
    shadowTint: "#141a18",
    shadowAmt: 0.1,
    grainSigma: 0.045,
    grainSize: 1.7,
    grainChroma: 0.15,
  }),
  stock({
    id: "aerochrome",
    name: "AEROCHROME",
    category: "lab",
    meta: "COLOUR INFRARED · †2009",
    hint: "foliage turns scarlet",
    note: "Military false-colour infrared: near-IR recorded as red, red as green, green as blue. Healthy leaves glow scarlet and pink, skies go deep blue. Once used to spot camouflage.",
    // Hue-mask emulation: foliage → scarlet, reds → yellow, sky deep blue,
    // water dark. A linear IR estimate turned water purple.
    hue12: [30, 20, -70, -100, -130, -160, 40, 10, 0, 0, 0, 15],
    satBand: [1, 0.7, 1.3, 1.35, 1.35, 1.3, 1.1, 1.2, 1.15, 1, 1, 1],
    lumBand: [1.05, 1.05, 1.1, 1.12, 1.12, 1.08, 0.72, 0.8, 0.88, 1, 1, 1],
    con: 0.2,
    sat: 1.15,
    grainSigma: 0.02,
    grainSize: 1.4,
    grainChroma: 0.15,
  }),
  stock({
    id: "expired",
    name: "EXPIRED ROLL",
    category: "lab",
    meta: "BEST BEFORE 2004 · ROLL LOTTERY",
    hint: "reroll = new roll",
    note: "Years in a hot drawer: base fog, a cast you can't predict — Kodak magenta, Fuji green, Agfa cyan — and grain climbing out of the shadows. Hit REROLL to open another roll.",
    lottery: true,
    con: -0.25,
    sat: 0.72,
    gain: [0.95, 0.89, 0.72],
    grainSigma: 0.05,
    grainSize: 1.9,
    grainChroma: 0.35,
    leak: 0.2,
    dust: 0.3,
  }),
  stock({
    id: "faded70s",
    name: "FADED '70S PRINT",
    category: "lab",
    meta: "EKTACOLOR · 50 YEARS IN A SHOEBOX",
    hint: "the cyan dye is gone",
    note: "That magenta-orange cast isn't pink added — it's cyan lost. Cyan and yellow dyes fade first, leaving maroon blacks, mauve mids and paper the colour of tea.",
    ramp: ["#592636", "#a97b8a", "#f4e6cc"],
    con: -0.1,
    sat: 0.85,
    border: "print",
    paper: "#efe6d2",
    dust: 0.25,
    grainSigma: 0.01,
    grainSize: 3,
    grainChroma: 0.2,
  }),

  // ── CAMERAS ─────────────────────────────────────────────────────────────
  stock({
    id: "sx70",
    name: "SX-70",
    category: "camera",
    meta: "INTEGRAL · POLAROID · 1972",
    hint: "soft, warm, dreamy",
    note: "Land's folding miracle. Soft and muted, blue-ish shadows, warm cream highlights, no grain at all — just the slow mottle of dye diffusing through the layers.",
    ramp: ["#1e292b", "#78756b", "#f3e6c9"],
    con: -0.15,
    sat: 0.75,
    bands: {
      R: { h: 5, s: -10 },
      Y: { s: -20 },
      G: { h: 15, s: -25 },
      A: { s: -15 },
      B: { h: 5, s: -25 },
    },
    glow: 0.15,
    glowColor: "#fff1dc",
    glowThreshold: 0.7,
    glowRadius: 0.015,
    grainSigma: 0.015,
    grainSize: 24,
    grainChroma: 0.3,
    border: "polaroid",
    paper: "#f3f1ea",
  }),
  stock({
    id: "polaroid600",
    name: "POLAROID 600",
    category: "camera",
    meta: "INTEGRAL · FLASH · 1981",
    hint: "flash-lit party instant",
    note: "The box camera with the built-in flash: punchier than SX-70, faces bright in the middle and the room falling into the dark behind them.",
    ramp: ["#1c2628", "#78756c", "#f4e9d0"],
    con: 0.1,
    sat: 0.9,
    bands: {
      G: { h: 12, s: -20 },
      B: { h: 5, s: -15 },
    },
    flash: 0.55,
    grainSigma: 0.012,
    grainSize: 20,
    grainChroma: 0.3,
    border: "polaroid",
    paper: "#f4f2ec",
  }),
  stock({
    id: "instax",
    name: "INSTAX MINI",
    category: "camera",
    meta: "INSTANT · 54×86 · 1998",
    hint: "cool, crisp, credit-card",
    note: "Fuji's instant: cooler and crisper than Polaroid, green-black shadows, the narrow credit-card frame clipped to a corkboard.",
    ramp: ["#1b2422", "#777874", "#f5f6f2"],
    con: 0.15,
    sat: 1.05,
    bands: { G: { h: 8 }, B: { s: 5 } },
    grainSigma: 0.01,
    grainSize: 16,
    grainChroma: 0.25,
    border: "instax",
    paper: "#f7f7f4",
  }),
  stock({
    id: "expiredpolaroid",
    name: "EXPIRED POLAROID",
    category: "camera",
    meta: "INTEGRAL · LONG DEAD",
    hint: "chemistry gone strange",
    note: "Instant film past its life: reagent that didn't spread, amber or teal-and-pink casts, washed blacks. Each reroll pulls a different pack from the box.",
    lottery: true,
    ramp: ["#2a2620", "#867a6a", "#e1d6bd"],
    con: -0.35,
    sat: 0.55,
    shadowTint: "#1c4a55",
    shadowAmt: 0.25,
    highTint: "#f4c7c8",
    highAmt: 0.2,
    leak: 0.35,
    leakColor: "#e0b25a",
    grainSigma: 0.02,
    grainSize: 22,
    grainChroma: 0.4,
    border: "polaroid",
    paper: "#ede6d3",
  }),
  stock({
    id: "holga",
    name: "HOLGA 120",
    category: "camera",
    meta: "PLASTIC LENS · MEDIUM FORMAT",
    hint: "leaks, tunnel, soft edge",
    note: "A $20 plastic camera from Hong Kong. Soft corners, colour fringing, a heavy brown vignette and the light leaks it's famous for — tape optional.",
    ramp: ["#120c0a", "#77706a", "#faf2e0"],
    con: 0.25,
    sat: 1.25,
    soft: 0.012,
    ca: 0.0025,
    vignette: 0.65,
    vignetteFalloff: 0.45,
    vignetteColor: "#1a0e06",
    leak: 0.6,
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0.25,
  }),
  stock({
    id: "diana",
    name: "DIANA F",
    category: "camera",
    meta: "PLASTIC LENS · 1960s",
    hint: "pastel bloom, dreamy",
    note: "The Holga's older, gentler cousin. Plastic-lens bloom on everything bright, pastel colour, a softer tunnel.",
    ramp: ["#221c1c", "#80786f", "#fbf3e6"],
    con: 0.05,
    sat: 0.92,
    soft: 0.01,
    ca: 0.0015,
    glow: 0.3,
    glowColor: "#fff3e6",
    glowThreshold: 0.6,
    glowRadius: 0.02,
    vignette: 0.5,
    vignetteFalloff: 0.35,
    vignetteColor: "#2a1a10",
    leak: 0.3,
    leakColor: "#ff7a4a",
    grainSigma: 0.025,
    grainSize: 1.6,
    grainChroma: 0.2,
  }),
  stock({
    id: "disposable",
    name: "DISPOSABLE FLASH",
    category: "camera",
    meta: "27 EXP · '98 DATE BACK",
    hint: "flash + orange date",
    note: "A single-use camera at a birthday party: flash-hot faces, the room dropping to black, plastic-lens corners — and the orange LED date burned into the corner of every frame.",
    wbLin: [0.98, 1, 1.03],
    ramp: ["#141a16", "#737671", "#f6f7f2"],
    con: 0.2,
    sat: 1.1,
    bands: {
      R: { h: 4, s: 10 },
      O: { h: 3, s: -5 },
      G: { h: 10, s: 10 },
      B: { h: 5, s: 10 },
    },
    flash: 1,
    soft: 0.005,
    ca: 0.001,
    vignette: 0.3,
    grainSigma: 0.045,
    grainSize: 1.8,
    grainChroma: 0.35,
    dateStamp: true,
  }),
  stock({
    id: "parr",
    name: "SEASIDE FLASH",
    category: "camera",
    meta: "AFTER MARTIN PARR · 1986",
    hint: "flash in daylight, loud",
    note: "After Martin Parr's New Brighton: fill-flash in broad daylight, colour turned up until it's slightly vulgar — sunburn, ice-cream and plastic.",
    ramp: ["#101010", "#737270", "#fbf8f0"],
    con: 0.3,
    sat: 1.35,
    bands: {
      R: { s: 25 },
      Y: { s: 25 },
      B: { s: 25 },
    },
    flash: 0.5,
    grainSigma: 0.02,
    grainSize: 1.4,
    grainChroma: 0.2,
  }),
  stock({
    id: "super8",
    name: "SUPER 8 FRAME",
    category: "camera",
    meta: "KODACHROME 40 · 5.8×4MM",
    hint: "home-movie still",
    note: "One frame of a 1970s home movie: a postage-stamp of Kodachrome blown up, so the grain is huge, the highlights bloom, and the gate's rounded corners show.",
    wbLin: [1.05, 1, 0.92],
    ramp: ["#140e0a", "#6f675e", "#f7eedc"],
    con: 0.3,
    sat: 1.15,
    bands: { R: { s: 15 }, B: { h: -10 } },
    glow: 0.2,
    glowColor: "#ffb070",
    glowThreshold: 0.7,
    glowRadius: 0.012,
    soft: 0.004,
    grainSigma: 0.065,
    grainSize: 2.6,
    grainChroma: 0.2,
    vignette: 0.25,
    border: "gate",
    paper: "#050505",
  }),
  stock({
    id: "brownie",
    name: "BROWNIE SNAPSHOT",
    category: "camera",
    meta: "VERICHROME · DECKLE · 1940s",
    hint: "scalloped family print",
    note: "A box-camera snapshot on orthochromatic-ish film: reds go dark, skies blow white, a meniscus lens softens the edges, and the drugstore printed it with a scalloped deckle edge.",
    mono: [0.1, 0.45, 0.45],
    tone: ["#1d1712", "#7b7063", "#f1e8d6"],
    toneMix: 1,
    con: 0.15,
    soft: 0.008,
    vignette: 0.35,
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0,
    border: "deckle",
    paper: "#f4eedf",
  }),

  // ── ANTIQUE ─────────────────────────────────────────────────────────────
  stock({
    id: "trix",
    name: "TRI-X 400",
    category: "antique",
    meta: "ISO 400 · B&W · 1954",
    hint: "the reportage b&w",
    note: "The black-and-white of photojournalism. Panchromatic but blue-hungry, so skies print lighter than a plain desaturate; gritty, crisp grain.",
    mono: PAN_TRIX,
    tone: ["#0a0a0a", "#7a7a79", "#f5f5f3"],
    toneMix: 1,
    con: 0.3,
    grainSigma: 0.055,
    grainSize: 2,
    grainChroma: 0,
  }),
  stock({
    id: "hp5push",
    name: "HP5 @ 3200",
    category: "antique",
    meta: "ISO 400 PUSHED 3 STOPS",
    hint: "pushed, black, clumpy",
    note: "Ilford HP5 pushed three stops for a dark club: blacks gone, contrast high, grain soft and clumping like smoke.",
    mono: [0.3, 0.48, 0.22],
    tone: ["#060606", "#757575", "#f6f6f4"],
    toneMix: 1,
    con: 0.45,
    grainSigma: 0.09,
    grainSize: 2.8,
    grainChroma: 0,
  }),
  stock({
    id: "sepia",
    name: "SEPIA TONED",
    category: "antique",
    meta: "SULPHIDE TONER",
    hint: "warm brown silver",
    note: "Silver converted to silver sulphide: warm browns that also happen to make the print last for centuries.",
    mono: PAN,
    tone: ["#1f1610", "#8c6c4c", "#f5ebda"],
    toneMix: 1,
    con: 0.2,
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0,
    vignette: 0.2,
  }),
  stock({
    id: "selenium",
    name: "SELENIUM SPLIT",
    category: "antique",
    meta: "SEPIA + SELENIUM",
    hint: "cream highs, plum blacks",
    note: "A darkroom split-tone: highlights bleached and sepia'd to cream, shadows pushed to a purple-black by selenium. Fine-art prints from the 80s.",
    mono: PAN,
    tone: ["#1d1820", "#7c7068", "#e9d7bc"],
    toneMix: 1,
    con: 0.3,
    grainSigma: 0.025,
    grainSize: 1.5,
    grainChroma: 0,
  }),
  stock({
    id: "tintype",
    name: "TINTYPE",
    category: "antique",
    meta: "WET COLLODION · 1856",
    hint: "red-blind, on iron",
    note: "Silver on black-lacquered iron, sensitive only to blue light: lips, freckles and tomatoes go black, blue eyes go ghostly pale, skies burn white. No paper, so no true white.",
    mono: [0, 0.08, 0.92],
    tone: ["#0e0b09", "#5a5247", "#cfc6b3"],
    toneMix: 1,
    con: 0.25,
    wb: [1.02, 1, 0.95],
    soft: 0.01,
    vignette: 0.55,
    grainSigma: 0.02,
    grainSize: 1.4,
    grainChroma: 0,
    border: "pour",
    paper: "#b8ae98",
    dust: 0.4,
    scratches: 0.5,
  }),
  stock({
    id: "daguerreotype",
    name: "DAGUERREOTYPE",
    category: "antique",
    meta: "SILVERED COPPER · 1839",
    hint: "mirror, mat, tarnish",
    note: "The first photograph you could buy: a mirror-polished silver plate under a brass mat, cool grey-blue, with rainbow tarnish — blue, violet, gold — creeping in from the edge.",
    mono: [0.02, 0.15, 0.83],
    tone: ["#1a1e22", "#7d8389", "#dcdfdc"],
    toneMix: 1,
    con: -0.15,
    glow: 0.2,
    glowColor: "#e8ecf0",
    glowThreshold: 0.6,
    glowRadius: 0.02,
    grainSigma: 0.01,
    grainSize: 1.2,
    grainChroma: 0,
    border: "oval",
    paper: "#b8913e",
    dust: 0.3,
  }),
  stock({
    id: "autochrome",
    name: "AUTOCHROME",
    category: "antique",
    meta: "LUMIÈRE · POTATO STARCH · 1907",
    hint: "dyed-starch pointillism",
    note: "The first practical colour: a glass plate dusted with potato-starch grains dyed orange, green and violet, lampblack in the gaps. Colour as soft pointillism.",
    exposure: -0.2,
    wbLin: [1.02, 1.03, 0.9],
    ramp: ["#16130e", "#696350", "#e8e0c2"],
    con: -0.1,
    sat: 0.65,
    bands: { R: { h: 5 }, B: { h: 12, s: -20 } },
    mosaic: 1,
    vignette: 0.35,
    grainSigma: 0.01,
    grainSize: 1.2,
    grainChroma: 0,
  }),
  stock({
    id: "cyanotype",
    name: "CYANOTYPE",
    category: "antique",
    meta: "IRON SALTS · HERSCHEL 1842",
    hint: "prussian blue, sun print",
    note: "Iron salts brushed on paper and laid in the sun turn Prussian blue wherever light lands. The blueprint — and Anna Atkins' algae — never reach a true black.",
    mono: PAN,
    tone: ["#0b1d3a", "#3f70a6", "#f1efe6"],
    toneMix: 1,
    con: 0.2,
    grainSigma: 0.02,
    grainSize: 6,
    grainChroma: 0,
    border: "deckle",
    paper: "#f1efe6",
  }),
  stock({
    id: "teacyan",
    name: "TEA-TONED CYANOTYPE",
    category: "antique",
    meta: "CYANOTYPE + TANNIN",
    hint: "steeped plum-brown",
    note: "Soak a cyanotype in strong tea and the tannins turn Prussian blue to plum and brown, the paper to parchment.",
    mono: PAN,
    tone: ["#2a2026", "#6e5b5a", "#e9dcc0"],
    toneMix: 1,
    con: 0.15,
    grainSigma: 0.02,
    grainSize: 6,
    grainChroma: 0,
    border: "deckle",
    paper: "#e9dcc0",
  }),
  stock({
    id: "vandyke",
    name: "VAN DYKE BROWN",
    category: "antique",
    meta: "IRON-SILVER · 1889",
    hint: "chocolate on rag",
    note: "Named for the brown of Van Dyck's paintings: an iron-silver print in deep chocolate fading to warm cream on cotton paper.",
    mono: PAN,
    tone: ["#22140c", "#6f4a30", "#efe3cb"],
    toneMix: 1,
    con: 0.1,
    grainSigma: 0.02,
    grainSize: 5,
    grainChroma: 0,
    vignette: 0.15,
    border: "print",
    paper: "#efe3cb",
  }),
  stock({
    id: "albumen",
    name: "ALBUMEN PRINT",
    category: "antique",
    meta: "EGG WHITE · GOLD TONED · 1850",
    hint: "purple-brown, yellowed",
    note: "Egg-white paper, gold-toned to purple-brown — the dominant print of the 19th century, now yellowed in the highlights and crazed with fine cracks.",
    mono: PAN,
    tone: ["#2c1a1e", "#8a6553", "#dccca6"],
    toneMix: 1,
    con: 0.15,
    grainSigma: 0.015,
    grainSize: 3,
    grainChroma: 0,
    vignette: 0.25,
    vignetteColor: "#3a2410",
    dust: 0.3,
    scratches: 0.6,
    border: "print",
    paper: "#e4d6b4",
  }),
  stock({
    id: "platinum",
    name: "PLATINUM",
    category: "antique",
    meta: "PLATINOTYPE · 1873",
    hint: "long, neutral, matte",
    note: "Platinum metal sunk into cotton paper: the longest tonal scale in photography, neutral to cool, matte, blacks deep but never quite black. Stieglitz's medium.",
    mono: PAN,
    tone: ["#231f1b", "#7f786e", "#efe9dd"],
    toneMix: 1,
    con: -0.2,
    grainSigma: 0.012,
    grainSize: 4,
    grainChroma: 0,
  }),
  stock({
    id: "palladium",
    name: "PALLADIUM",
    category: "antique",
    meta: "PALLADIOTYPE · 1916",
    hint: "warm platinum",
    note: "Palladium replaced platinum when the war took the metal: the same impossible tonal range, warmer — browns where platinum gives greys.",
    mono: PAN,
    tone: ["#2d2318", "#8a755b", "#f2e9d6"],
    toneMix: 1,
    con: -0.2,
    grainSigma: 0.012,
    grainSize: 4,
    grainChroma: 0,
  }),
  stock({
    id: "handtint",
    name: "HAND-TINTED",
    category: "antique",
    meta: "OIL & WATERCOLOUR · 1900–1950",
    hint: "colour painted on b&w",
    note: "A black-and-white print coloured by hand with transparent dyes: the colour bleeds past the edges, pools on the cheeks, and vanishes in the shadows where the dye can't show.",
    mono: PAN,
    tone: ["#1e1813", "#8a7b68", "#f1e8d7"],
    toneMix: 1,
    con: 0.1,
    handTint: 1,
    grainSigma: 0.015,
    grainSize: 2,
    grainChroma: 0,
    vignette: 0.2,
  }),

  // ── AFTERDARK ───────────────────────────────────────────────────────────
  stock({
    id: "nightshot",
    name: "NIGHTSHOT",
    category: "afterdark",
    meta: "IR CAMCORDER · 1999",
    hint: "green IR camcorder",
    note: "A Handycam's NightShot mode: the IR filter swings away, an infrared lamp lights the room, and everything turns phosphor green — skin glowing, eyes bright, the edges falling into black.",
    mono: [1, 0.3, -0.2],
    tone: ["#020a04", "#0a2a0e", "#1f5c1c", "#4fa83a", "#d6ffcc"],
    toneMix: 1,
    exposure: 0.25,
    con: 0.3,
    flash: 1,
    glow: 0.45,
    glowColor: "#c8ffb0",
    glowThreshold: 0.6,
    glowRadius: 0.02,
    vignette: 0.4,
    grainSigma: 0.055,
    grainSize: 1.6,
    grainChroma: 0,
    scanlines: 0.08,
    hud: "rec",
  }),
  stock({
    id: "trailcam",
    name: "TRAIL CAM",
    category: "afterdark",
    meta: "IR GAME CAMERA",
    hint: "grey IR + info bar",
    note: "A hunting camera strapped to a tree: grey infrared flash, a hot centre falling to black, and the info strip — camera, moon, temperature, timestamp — burned across the bottom.",
    mono: [0.6, 0.35, 0.05],
    tone: ["#050505", "#2a2a2a", "#7a7a7a", "#c4c4c4", "#f2f2f2"],
    toneMix: 1,
    con: 0.3,
    flash: 1,
    vignette: 0.5,
    grainSigma: 0.05,
    grainSize: 1.6,
    grainChroma: 0,
    hud: "trail",
  }),
  stock({
    id: "thermal",
    name: "THERMAL",
    category: "afterdark",
    meta: "FLIR · IRON PALETTE",
    hint: "white-hot iron palette",
    note: "A thermal camera reads heat, not light. Dark shapes and warm skin read hot against cold sky, mapped through the classic 'iron' palette from violet to white-hot.",
    // Colour kept through the grade so skin (darkened in the R/O bands) reads hottest.
    tone: ["#fffbe6", "#ffbe0b", "#f72585", "#3a0ca3", "#05010f"],
    toneMix: 1,
    con: 0.25,
    bands: { R: { l: -35 }, O: { l: -40 } },
    simplify: 3,
    grainSigma: 0.01,
    grainSize: 1.2,
    grainChroma: 0,
    hud: "thermal",
  }),
  stock({
    id: "vhs",
    name: "VHS FOUND",
    category: "afterdark",
    meta: "SP · 2004 · ANALOG HORROR",
    hint: "chroma bleed, tracking, PLAY",
    note: "Somebody's tape from a lake house: washed blacks, colour bleeding sideways off every edge, a tracking band, and the deck's PLAY and date on screen.",
    ramp: ["#1a1a1e", "#6f6d6a", "#ecebe4"],
    con: -0.1,
    sat: 0.85,
    bleed: 10,
    sharpen: 0.35,
    smear: 0.12,
    scanlines: 0.07,
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0.5,
    hud: "vhs",
  }),
  stock({
    id: "witchhouse",
    name: "WITCH HOUSE",
    category: "afterdark",
    meta: "△ 2010 · SALEM",
    hint: "solarized, smeared, △",
    note: "Witch-house cover art, 2010: a grainy occult photograph, half-solarized, rows dragged sideways like a chewed tape, a triangle floating above.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#2a2a33", "#111117", "#5a5a66", "#b8b8c4", "#ececf2"],
    toneMix: 1,
    con: 0.4,
    smear: 0.55,
    vignette: 0.4,
    grainSigma: 0.07,
    grainSize: 1.8,
    grainChroma: 0,
    hud: "witch",
  }),
  stock({
    id: "xerox",
    name: "XEROX ZINE",
    category: "afterdark",
    meta: "PHOTOCOPY · SLASH '77",
    hint: "binary toner, torn edge",
    note: "Run through a photocopier until only black toner and paper are left — the punk-zine look Whole Lotta Red's cover borrowed from Slash magazine.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#141414", "#141414", "#7a776f", "#f0ece2", "#f0ece2"],
    toneMix: 1,
    con: 0.6,
    quant: "threshold",
    cell: 6,
    border: "grunge",
    paper: "#121212",
    grainSigma: 0.015,
    grainSize: 2,
    grainChroma: 0,
  }),
  stock({
    id: "halftone",
    name: "HALFTONE PRINT",
    category: "afterdark",
    meta: "SCREENPRINT · 45°",
    hint: "big red dots on paper",
    note: "One ink, one screen at 45°: the photo becomes dots that grow in the shadows and vanish in the light. Gig posters and the backs of merch tees.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#c1272d", "#c1272d", "#d98a7a", "#efe9dc", "#efe9dc"],
    toneMix: 1,
    con: 0.3,
    quant: "halftone",
    cell: 20,
    grainSigma: 0.012,
    grainSize: 2,
    grainChroma: 0,
  }),
  stock({
    id: "riso",
    name: "RISO MISPRINT",
    category: "afterdark",
    meta: "RISOGRAPH · 2 DRUMS",
    hint: "fluoro pink + blue, off-register",
    note: "Two soy-ink drums — fluoro pink and blue — printed one after the other and never quite lined up. Grainy fills, a blue edge peeking out where the plates slipped.",
    mono: [0.3, 0.45, 0.25],
    tone: ["#1d3d8f", "#0078bf", "#ff48b0", "#ffb3d9", "#f2ede3"],
    toneMix: 1,
    con: 0.35,
    quant: "bayer",
    levels: 5,
    cell: 5,
    plates: [{ dx: 12, dy: 8, color: "#0078bf", amount: 0.7 }],
    grainSigma: 0.035,
    grainSize: 2.2,
    grainChroma: 0,
  }),
  stock({
    id: "grungeangel",
    name: "GRUNGE ANGEL",
    category: "afterdark",
    meta: "OPIUM · COVER ART",
    hint: "cream dither, Y+R fringe",
    note: "The underground-rap cover treatment: three-tone ordered dither in cream and ink, yellow and red plates slipping off the edges, inside a torn photocopy border.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#141210", "#141210", "#8c8678", "#ede3cc", "#ede3cc"],
    toneMix: 1,
    con: 0.35,
    quant: "bayer",
    levels: 3,
    cell: 5,
    glow: 0.3,
    glowColor: "#ede3cc",
    glowThreshold: 0.5,
    glowRadius: 0.03,
    plates: [
      { dx: 9, dy: 0, color: "#e8c23a", amount: 0.9 },
      { dx: -7, dy: 5, color: "#c8302a", amount: 0.75 },
    ],
    border: "grunge",
    paper: "#0d0b10",
  }),
  stock({
    id: "cutoutblue",
    name: "CUTOUT BLUE",
    category: "afterdark",
    meta: "POSTERIZE · 5 TONES",
    hint: "flat blue screenprint",
    note: "Photoshop's Cutout filter by way of a screen-printer: shapes simplified, five flat blues, no gradients, a ragged frame.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#0b1330", "#162a5c", "#23407a", "#6e95c8", "#e6eef7"],
    toneMix: 1,
    con: 0.3,
    quant: "posterize",
    levels: 5,
    simplify: 6,
    border: "grunge",
    paper: "#0b1330",
    grainSigma: 0.015,
    grainSize: 1.4,
    grainChroma: 0,
  }),
  stock({
    id: "sepiaglow",
    name: "SEPIA GLOW",
    category: "afterdark",
    meta: "DARK ANGELCORE",
    hint: "warm glow, torn edge",
    note: "The soft version: a sepia gradient map with a bloom like candlelight through stained glass, grain, and the same torn border.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#2a1a0e", "#5a3a20", "#8a5a32", "#c4935e", "#f0d8ae"],
    toneMix: 1,
    con: 0.15,
    glow: 0.55,
    glowColor: "#f0d8ae",
    glowThreshold: 0.35,
    glowRadius: 0.04,
    vignette: 0.3,
    vignetteColor: "#2a1a0e",
    border: "grunge",
    paper: "#24150b",
    grainSigma: 0.03,
    grainSize: 1.6,
    grainChroma: 0,
  }),
  stock({
    id: "rustdither",
    name: "RUST DITHER",
    category: "afterdark",
    meta: "3-TONE · OXIDE",
    hint: "brown-orange dither",
    note: "The same dither in oxide: dried-blood brown, rust and a pale tan, no fringe, framed.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#1c0f0a", "#1c0f0a", "#8c3b1e", "#e3b07a", "#e3b07a"],
    toneMix: 1,
    con: 0.35,
    quant: "bayer",
    levels: 3,
    cell: 5,
    border: "grunge",
    paper: "#1c0f0a",
  }),
  stock({
    id: "tricolour",
    name: "TRICOLOUR",
    category: "afterdark",
    meta: "NAVY · RED · BONE",
    hint: "red-fringed dither",
    note: "Navy, blood-red and bone in an ordered dither, a red plate slipping off the dark edges — the loudest of the angel variants.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#13204a", "#13204a", "#c1272d", "#f2efe6", "#f2efe6"],
    toneMix: 1,
    con: 0.35,
    quant: "bayer",
    levels: 3,
    cell: 5,
    plates: [{ dx: 9, dy: 2, color: "#ff5a3c", amount: 0.8 }],
    border: "grunge",
    paper: "#13204a",
  }),
  stock({
    id: "gigposter",
    name: "GIG POSTER",
    category: "afterdark",
    meta: "DUOTONE · FLAT",
    hint: "flat blood-red duotone",
    note: "Five flat tones from black-cherry to bone, shapes simplified until it could be pulled through a silkscreen.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#1a0505", "#5c0a0e", "#c1272d", "#e88a6a", "#f4ead8"],
    toneMix: 1,
    con: 0.3,
    quant: "posterize",
    levels: 5,
    simplify: 5,
    grainSigma: 0.012,
    grainSize: 1.4,
    grainChroma: 0,
  }),
  stock({
    id: "onebit",
    name: "1-BIT",
    category: "afterdark",
    meta: "ORDERED · 2 COLOURS",
    hint: "two colours, Bayer dots",
    note: "Two colours and an ordered dither — early-Mac and Game Boy Camera at once. For the classic Atkinson version, use PIXEL → COLOURS Mono + PATTERN Atkinson.",
    mono: [0.3, 0.55, 0.15],
    tone: ["#1b1c26", "#1b1c26", "#82808a", "#e9e6dc", "#e9e6dc"],
    toneMix: 1,
    con: 0.2,
    quant: "bayer",
    levels: 2,
    cell: 3,
  }),
  stock({
    id: "softgrunge",
    name: "SOFT GRUNGE '14",
    category: "afterdark",
    meta: "TUMBLR · 2014",
    hint: "matte, green cast, leak",
    note: "Peak Tumblr: blacks faded to grey, a faint green cast, a warm leak burning in from the corner, grain everywhere.",
    wbLin: [0.97, 1.03, 0.98],
    ramp: ["#2a2d29", "#7a7c74", "#ece9df"],
    con: -0.1,
    sat: 0.85,
    leak: 0.65,
    leakColor: "#ff7a3a",
    leakAngle: -0.6,
    grainSigma: 0.035,
    grainSize: 1.5,
    grainChroma: 0.2,
  }),
  stock({
    id: "deepfried",
    name: "DEEP FRIED",
    category: "afterdark",
    meta: "JPEG Q≈5 · ×3",
    hint: "oversaturated, crunched",
    note: "Saturation through the roof, halos on every edge, then saved as a JPEG three times at rock-bottom quality. Crunch on purpose.",
    con: 0.6,
    sat: 2.2,
    sharpen: 1.2,
    crunch: 1,
  }),
  stock({
    id: "ccd07",
    name: "CCD DIGICAM '07",
    category: "afterdark",
    meta: "CYBER-SHOT · FLASH ON",
    hint: "flash, crunch, date",
    note: "A 7-megapixel point-and-shoot with the flash forced on: blown subject, the room falling to black, cool CCD colour, oversharpened, a mid-quality JPEG and an orange date.",
    wbLin: [0.94, 0.98, 1.08],
    ramp: ["#141018", "#6e6c70", "#fbf8f4"],
    con: 0.25,
    sat: 1.1,
    bands: { R: { s: 15 }, M: { s: 15 } },
    flash: 1,
    sharpen: 0.8,
    crunch: 0.5,
    dateStamp: true,
    grainSigma: 0.02,
    grainSize: 1.2,
    grainChroma: 0.4,
  }),

  // ── PS2 & PAINT ─────────────────────────────────────────────────────────
  stock({
    id: "ps2red",
    name: "PS2 RED",
    category: "polypaint",
    meta: "LOW-POLY · CUT-OUT",
    hint: "low-poly you on red",
    note: "You as a 2003 game model: the silhouette cut into straight polygon edges, each facet airbrushed soft inside, standing on flat red. After Gao Hang's \u201csharp blurriness\u201d.",
    stylize: "ps2",
    stylizeBg: "#ec1c1c",
    sat: 1.15,
    grainSigma: 0.02,
    grainSize: 1.2,
    grainChroma: 0,
  }),
  stock({
    id: "ps2lime",
    name: "PS2 LIME",
    category: "polypaint",
    meta: "LOW-POLY · CUT-OUT",
    hint: "low-poly you on lime",
    note: "The San Andreas edit: low-poly cut-out on screaming lime green.",
    stylize: "ps2",
    stylizeBg: "#96f000",
    sat: 1.15,
    grainSigma: 0.02,
    grainSize: 1.2,
    grainChroma: 0,
  }),
  stock({
    id: "ps2sky",
    name: "PS2 SKY",
    category: "polypaint",
    meta: "LOW-POLY · CUT-OUT",
    hint: "low-poly you on blue",
    note: "Low-poly cut-out against a flat skybox blue — the loading-screen version.",
    stylize: "ps2",
    stylizeBg: "#3d9cf0",
    sat: 1.15,
    grainSigma: 0.02,
    grainSize: 1.2,
    grainChroma: 0,
  }),
  stock({
    id: "airbrush",
    name: "AIRBRUSH CANVAS",
    category: "polypaint",
    meta: "ACRYLIC · TAPE-MASKED",
    hint: "faceted airbrush painting",
    note: "The whole frame broken into big tape-masked facets, each sprayed as a soft gradient, on canvas tooth — a painting of a low-poly world.",
    stylize: "airbrush",
    sat: 1.15,
    grainSigma: 0.025,
    grainSize: 1.8,
    grainChroma: 0,
  }),
  stock({
    id: "sticker",
    name: "STICKER",
    category: "polypaint",
    meta: "PICSART · PHONE EDIT",
    hint: "cut-out, black outline, sky",
    note: "A phone-app collage: you cut out, outlined thick in black, colour cranked, dropped onto a cartoon sky — the way Frank Dorrey makes his on an iPhone with PicsArt.",
    stylize: "sticker",
    con: 0.35,
    sat: 1.8,
    exposure: 0.1,
  }),
  stock({
    id: "impasto",
    name: "IMPASTO",
    category: "polypaint",
    meta: "OIL · PALETTE KNIFE",
    hint: "thick oil paint",
    note: "Painted over the photo in thick oil: shapes flattened into strokes, colour pushed, light raking across the ridges of paint.",
    stylize: "impasto",
    con: 0.15,
    sat: 1.3,
  }),

  // ── EARTH & AUTEUR ──────────────────────────────────────────────────────
  stock({
    id: "kinfolk",
    name: "KINFOLK EARTH",
    category: "earth",
    meta: "MATTE · LINEN · OAK",
    hint: "muted, warm matte",
    note: "The slow-living magazine look: lifted blacks, linen whites, every colour pulled back toward clay and oatmeal; greens barely there.",
    wbLin: [1.03, 1, 0.96],
    ramp: ["#2b2620", "#7d766c", "#efe9df"],
    con: -0.2,
    sat: 0.7,
    bands: {
      R: { h: 6, s: -30 },
      O: { s: -10, l: 5 },
      Y: { h: -8, s: -35 },
      G: { h: -15, s: -45, l: -5 },
      A: { s: -50 },
      B: { h: -10, s: -50 },
    },
    grainSigma: 0.012,
    grainSize: 1.3,
    grainChroma: 0.1,
  }),
  stock({
    id: "nordic",
    name: "NORDIC MATTE",
    category: "earth",
    meta: "OVERCAST · FJORD · BIRCH",
    hint: "cool, airy, washed",
    note: "Scandinavian overcast: a stop bright, cool and airy, blue-grey shadows, greens and blues bleached toward stone.",
    exposure: 0.25,
    wbLin: [0.98, 1, 1.03],
    ramp: ["#262b2e", "#808586", "#f1f3f2"],
    con: -0.2,
    sat: 0.62,
    bands: {
      G: { h: 10, s: -45 },
      B: { s: -40, l: 10 },
    },
    grainSigma: 0.01,
    grainSize: 1.2,
    grainChroma: 0.1,
  }),
  stock({
    id: "golden",
    name: "GOLDEN MATTE",
    category: "earth",
    meta: "LAST HOUR OF SUN",
    hint: "honey bloom, soft blacks",
    note: "Golden hour held on to: honey highlights blooming softly, blacks lifted to warm brown, skies and greens let go so the warmth carries the frame.",
    wbLin: [1.08, 1, 0.85],
    ramp: ["#2e2219", "#82725f", "#fff0d4"],
    con: 0.05,
    sat: 0.95,
    bands: {
      O: { s: 10, l: 5 },
      Y: { h: -8, s: 5 },
      G: { h: -20, s: -25 },
      A: { s: -30 },
      B: { h: -10, s: -45 },
    },
    highTint: "#ffd9a0",
    highAmt: 0.15,
    glow: 0.25,
    glowColor: "#ffd29a",
    glowThreshold: 0.7,
    glowRadius: 0.025,
    grainSigma: 0.015,
    grainSize: 1.4,
    grainChroma: 0.1,
  }),
  stock({
    id: "forest",
    name: "MOODY FOREST",
    category: "earth",
    meta: "MOSS · FERN · WET BARK",
    hint: "leaves become moss",
    note: "Under the canopy in the rain: yellow-greens dragged down to moss, blues nearly gone, teal-black shadows — but skin kept warm.",
    exposure: -0.15,
    ramp: ["#121a16", "#68695f", "#e6dfd0"],
    con: 0.15,
    sat: 0.7,
    bands: {
      R: { s: -20 },
      O: { s: -5 },
      Y: { h: 15, s: -40, l: -10 },
      G: { h: 10, s: -35, l: -20 },
      A: { s: -40, l: -10 },
      B: { s: -55, l: -10 },
    },
    shadowTint: "#1c2b25",
    shadowAmt: 0.18,
    highTint: "#eadbc2",
    highAmt: 0.06,
    vignette: 0.25,
    grainSigma: 0.02,
    grainSize: 1.5,
    grainChroma: 0.1,
  }),
  stock({
    id: "terracotta",
    name: "TERRACOTTA",
    category: "earth",
    meta: "DESERT · ADOBE · SAGE",
    hint: "clay, sand, dusty sky",
    note: "Desert palette: reds to fired clay, yellows to sand, greens to dry sage, the sky a dusty blue-grey — everything sun-baked.",
    wbLin: [1.07, 1, 0.88],
    ramp: ["#2a1c16", "#86705e", "#f7e6cf"],
    con: 0.1,
    sat: 0.85,
    bands: {
      R: { h: 12, s: -10 },
      O: { s: 10, l: -5 },
      Y: { h: -10, s: -15 },
      G: { h: -30, s: -55 },
      A: { s: -40 },
      B: { h: -15, s: -35, l: 5 },
    },
    grainSigma: 0.015,
    grainSize: 1.4,
    grainChroma: 0.1,
  }),
  stock({
    id: "pastel",
    name: "PASTEL SYMMETRY",
    category: "earth",
    meta: "AFTER WES ANDERSON",
    hint: "salmon, butter, mint",
    note: "Centred, symmetrical, candy-box: salmon, butter yellow, mint, powder blue and pink, everything a little lighter than life.",
    exposure: 0.1,
    ramp: ["#33292c", "#857a7a", "#fff4e8"],
    con: -0.1,
    sat: 1,
    bands: {
      R: { h: 8, l: 10 },
      Y: { s: 10, l: 10 },
      G: { h: 20, s: -20, l: 10 },
      A: { s: -30, l: 10 },
      B: { h: -10, s: -35, l: 15 },
      M: { s: 10, l: 10 },
    },
    grainSigma: 0.008,
    grainSize: 1.2,
    grainChroma: 0.05,
  }),
  stock({
    id: "hongkong",
    name: "HONG KONG NEON",
    category: "earth",
    meta: "AFTER WONG KAR-WAI · DOYLE",
    hint: "melancholy green, crimson",
    note: "Chungking Express and In the Mood for Love: fluorescent green melancholy, crimson and amber, pushed grain, highlights bleeding warm in the humidity.",
    wbLin: [0.95, 1.05, 0.96],
    ramp: ["#0b1612", "#6a6e62", "#ffe6c0"],
    con: 0.25,
    sat: 1.15,
    bands: {
      R: { h: -3, s: 30, l: -10 },
      Y: { h: -10, s: 10 },
      G: { h: 10, s: 15 },
      A: { s: 10 },
    },
    shadowTint: "#10241c",
    shadowAmt: 0.18,
    highTint: "#ffd9a0",
    highAmt: 0.12,
    glow: 0.3,
    glowColor: "#ff5a2a",
    glowThreshold: 0.72,
    glowRadius: 0.01,
    vignette: 0.3,
    grainSigma: 0.05,
    grainSize: 2,
    grainChroma: 0.25,
  }),
  stock({
    id: "leiter",
    name: "LEITER VEIL",
    category: "earth",
    meta: "AFTER SAUL LEITER · 1950s NY",
    hint: "through steamed glass",
    note: "Saul Leiter shot expired colour film through rain and steamed windows: hues muted to lavender and brown, the scene veiled — and one red umbrella left alive.",
    exposure: -0.05,
    ramp: ["#2e2833", "#7a7272", "#eae1d8"],
    con: -0.15,
    sat: 0.55,
    bands: {
      R: { s: 40 },
      Y: { h: -8, s: -30 },
      G: { h: -10, s: -60 },
      A: { s: -55 },
      B: { h: 15, s: -45 },
    },
    glow: 0.35,
    glowColor: "#f0e8e4",
    glowThreshold: 0.55,
    glowRadius: 0.03,
    grainSigma: 0.03,
    grainSize: 1.8,
    grainChroma: 0.15,
  }),
  stock({
    id: "shore",
    name: "SHORE 8×10",
    category: "earth",
    meta: "AFTER STEPHEN SHORE · 1970s",
    hint: "high-noon americana, no grain",
    note: "Uncommon Places: an 8×10 view camera at a Texas intersection at noon. High-key, pale cyan sky, flat light — and essentially no grain, which is the whole point.",
    exposure: 0.1,
    ramp: ["#1a1c1e", "#7b7c7a", "#f8f6ef"],
    con: -0.15,
    sat: 0.85,
    bands: {
      R: { h: 5, s: -10 },
      G: { h: -5, s: -15 },
      B: { h: -10, s: -60, l: 15 },
      A: { s: -55, l: 10 },
    },
    grainSigma: 0.003,
    grainSize: 1,
    grainChroma: 0,
  }),

  // ─── SCREENS & MACHINES ─────────────────────────────────────────────────
  stock({
    id: "crt",
    name: "CRT TRINITRON",
    category: "machine",
    meta: "APERTURE GRILLE · 1990s TV",
    hint: "scanlines + RGB stripes",
    note: "A Sony Trinitron: the picture drawn by an electron beam one scanline at a time, bright lines swelling fatter than dark ones, through vertical red-green-blue phosphor stripes, glowing behind the glass.",
    fx: "crt",
    fxMode: "trinitron",
    sat: 1.1,
  }),
  stock({
    id: "pvm",
    name: "PVM MONITOR",
    category: "machine",
    meta: "BROADCAST MONITOR · 480 LINES",
    hint: "sharp, fine scanlines",
    note: "The Sony PVM the retro-gaming crowd hunts down: a flat-ish broadcast monitor with razor scanlines and a fine grille — the CRT look at its cleanest.",
    fx: "crt",
    fxMode: "pvm",
    sat: 1.05,
  }),
  stock({
    id: "arcade",
    name: "ARCADE CRT",
    category: "machine",
    meta: "SLOT MASK · 224 LINES",
    hint: "fat lines, curved glass",
    note: "A 1980s arcade cabinet: 224 fat scanlines, a slot-mask phosphor pattern, heavy curved glass, misconverged colour edges and a lot of glow.",
    fx: "crt",
    fxMode: "arcade",
    sat: 1.25,
    con: 0.15,
  }),
  stock({
    id: "amberterm",
    name: "AMBER TERMINAL",
    category: "machine",
    meta: "P3 PHOSPHOR · MONOCHROME",
    hint: "orange mono monitor",
    note: "A monochrome terminal with amber P3 phosphor — the colour of 1980s office computers and every hacker movie since.",
    fx: "crt",
    fxMode: "amber",
    con: 0.2,
  }),
  stock({
    id: "greenterm",
    name: "GREEN PHOSPHOR",
    category: "machine",
    meta: "P1 PHOSPHOR · MONOCHROME",
    hint: "green mono monitor",
    note: "Green P1 phosphor on a curved monochrome tube: the original computer screen colour.",
    fx: "crt",
    fxMode: "green",
    con: 0.2,
  }),
  stock({
    id: "receipt",
    name: "RECEIPT",
    category: "machine",
    meta: "58 MM THERMAL · 203 DPI",
    hint: "printed on till paper",
    note: "A 58 mm thermal till printer: 384 dots across, 8 per millimetre, burned into heat-sensitive paper — with the unprintable margins, a tired print-head element or two, and the serrated cut.",
    fx: "receipt",
    fxMode: "fresh",
    fxScale: 384,
    fxInk: "#1f1f26",
    fxPaper: "#f5f3ee",
  }),
  stock({
    id: "receiptold",
    name: "FADED RECEIPT",
    category: "machine",
    meta: "THERMAL · WALLET-AGED",
    hint: "yellowed, fading print",
    note: "The same receipt after a summer in a wallet: paper gone cream, the thermal image fading to grey and dropping out in patches.",
    fx: "receipt",
    fxMode: "faded",
    fxScale: 384,
    fxInk: "#4d4651",
    fxPaper: "#ede2c6",
  }),
  stock({
    id: "mac1bit",
    name: "MAC 1-BIT",
    category: "machine",
    meta: "512×342 · ATKINSON · 1984",
    hint: "classic macintosh",
    note: "The original Macintosh: 512 pixels across, every one black or white, shaded with Bill Atkinson's dither — which only passes on three quarters of the error, so whites stay white.",
    fx: "onebit",
    fxMode: "atkinson",
    fxScale: 512,
    fxInk: "#000000",
    fxPaper: "#ffffff",
  }),
  stock({
    id: "obradinn",
    name: "OBRA DINN",
    category: "machine",
    meta: "1-BIT · BLUE NOISE",
    hint: "1-bit, blue-noise dither",
    note: "After Lucas Pope's Return of the Obra Dinn: strictly two colours, shaded by a blue-noise threshold pattern that never forms a visible grid.",
    fx: "onebit",
    fxMode: "blue",
    fxScale: 640,
    fxInk: "#333319",
    fxPaper: "#e5ffff",
  }),
  stock({
    id: "playdate",
    name: "PLAYDATE",
    category: "machine",
    meta: "400×240 · MEMORY LCD",
    hint: "grey 1-bit handheld",
    note: "The Playdate's 400×240 memory LCD: black on a warm silver-grey, no backlight, shaded with an ordered Bayer pattern.",
    fx: "onebit",
    fxMode: "bayer",
    fxScale: 400,
    fxInk: "#312f28",
    fxPaper: "#b1afa8",
  }),
  stock({
    id: "chunky1bit",
    name: "CHUNKY 1-BIT",
    category: "machine",
    meta: "1-BIT · FLOYD–STEINBERG",
    hint: "big dots, ink on paper",
    note: "One-bit with the dots blown up: Floyd–Steinberg error diffusion at 200 dots across, ink on off-white.",
    fx: "onebit",
    fxMode: "floyd",
    fxScale: 200,
    fxInk: "#141414",
    fxPaper: "#efebe0",
  }),
  stock({
    id: "depthmap",
    name: "DEPTH MAP",
    category: "machine",
    meta: "DEPTH ANYTHING V2 · ON DEVICE",
    hint: "near white, far black",
    note: "What a depth sensor sees: a neural network (Depth Anything V2, running on your device) guesses how far away every pixel is — near is white, far is black.",
    stylize: "depth",
  }),
  stock({
    id: "depthheat",
    name: "DEPTH HEAT",
    category: "machine",
    meta: "DEPTH · TURBO COLORMAP",
    hint: "distance as colour",
    note: "The same depth map through Google's Turbo colour scale: red is close, blue is far — the LiDAR / Kinect debug view.",
    stylize: "depthheat",
  }),
  stock({
    id: "depthlines",
    name: "DEPTH CONTOURS",
    category: "machine",
    meta: "DEPTH · ISOLINES",
    hint: "topographic lines",
    note: "Depth drawn as a topographic map: a line every step closer, every fifth one bolder, on black.",
    stylize: "depthlines",
    stylizeBg: "#f2f2ea",
  }),
  stock({
    id: "depthhaze",
    name: "DEPTH HAZE",
    category: "machine",
    meta: "DEPTH · ATMOSPHERE",
    hint: "far things fade into fog",
    note: "Uses the depth map photographically: everything far away sinks into pale haze, the subject stays clear.",
    stylize: "depthhaze",
    stylizeBg: "#c9d0d6",
  }),
  stock({
    id: "blobtrack",
    name: "BLOB TRACK",
    category: "machine",
    meta: "MACHINE VISION · ON DEVICE",
    hint: "boxes what's really there",
    note: "The TouchDesigner tracking look, done for real: object and face detectors running on your device find what's in the photo — people, faces, eyes, phones, cups, dogs — box each one with its label and confidence, and wire them together.",
    fx: "blob",
    fxMode: "boxes",
  }),
  stock({
    id: "blobinvert",
    name: "BLOB INVERT",
    category: "machine",
    meta: "MACHINE VISION · INVERTED",
    hint: "tracked boxes inverted",
    note: "Tracking with every detected thing flipped to negative.",
    fx: "blob",
    fxMode: "invert",
  }),
  stock({
    id: "blobmono",
    name: "BLOB FOCUS",
    category: "machine",
    meta: "MACHINE VISION · LOCK-ON",
    hint: "colour only where tracked",
    note: "The frame drops to dim grey; only the things the detectors found keep their colour.",
    fx: "blob",
    fxMode: "mono",
  }),
  stock({
    id: "datamosh",
    name: "DATAMOSH",
    category: "machine",
    meta: "P-FRAME BLOOM · H.264",
    hint: "codec smear",
    note: "A video with its keyframe deleted: the codec keeps applying motion vectors to a picture that isn't there, so 16-pixel macroblocks drag and bloom across the frame. A still has no motion, so LORES invents the vector field — NEW GRAIN rolls a new one.",
    stylize: "mosh",
    crunch: 0.5,
  }),
  stock({
    id: "moshmelt",
    name: "MOSH MELT",
    category: "machine",
    meta: "P-FRAME BLOOM · DOWNWARD",
    hint: "the image drips",
    note: "Datamosh with every motion vector pointing down: the picture melts and drips in blocks.",
    stylize: "melt",
    crunch: 0.5,
  }),
];

/**
 * The looks shown first (the BEST chip): one or two of the strongest from
 * every family, so a new user sees the range without wading through 100+.
 */
export const HERO_LOOKS = [
  "portra400",
  "gold200",
  "kodachrome64",
  "cinestill800t",
  "vision2383",
  "trix",
  "sx70",
  "disposable",
  "expired",
  "aerochrome",
  "golden",
  "hongkong",
  "cyanotype",
  "vhs",
  "nightshot",
  "riso",
  "deepfried",
  "ps2red",
  "crt",
  "receipt",
  "mac1bit",
  "depthheat",
  "blobtrack",
  "datamosh",
];

/** Which chip a look lives under: BEST if it's a hero, else its family. */
export function chipFor(id: string): string {
  if (HERO_LOOKS.includes(id)) return "best";
  return getStock(id)?.category ?? "best";
}

export function getStock(id: string): FilmStock | null {
  return FILM_STOCKS.find((s) => s.id === id) ?? null;
}
